const products = window.FRAMECO_PRODUCTS || [];
let cart = [], selectedSize = 'A3';
const A3_PRICE = 18, A1_PRICE = 28, DELIVERY = 3;

function byId(id){ return document.getElementById(id); }
function renderProducts(){ const grid=byId('product-grid'); if(!grid)return; grid.innerHTML=products.map(p=>`<article class="product" onclick="openProduct(${p.id})"><div class="product-image"><img src="${p.image}" alt="${p.name}"></div><div class="product-info"><span class="product-name">${p.name}</span><span>From ${A3_PRICE} JD</span></div></article>`).join(''); }
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const m=document.createElement('div');m.className='modal active';m.innerHTML=`<div class="modal-inner"><button class="modal-close" onclick="this.closest('.modal').remove()">×</button><img src="${p.image}" alt="${p.name}" style="margin-bottom:30px"><p class="eyebrow">PRODUCT | ARTWORK PAGE</p><h2>${p.name}</h2><p style="line-height:1.5;margin-bottom:30px">${p.desc}</p><div style="display:flex;gap:10px;margin-bottom:30px"><button class="size-button" onclick="selectSize(this,'A3')" style="flex:1;padding:20px;background:#111;color:#fff;border:1px solid #111">A3<br>29.7 × 42 cm<br>${A3_PRICE} JD</button><button class="size-button" onclick="selectSize(this,'A1')" style="flex:1;padding:20px;background:transparent;color:#111;border:1px solid #111">A1<br>59.4 × 84.1 cm<br>${A1_PRICE} JD</button></div><button class="button full" onclick="addToCart(${p.id},selectedSize);this.closest('.modal').remove()">ADD TO CART</button></div>`;document.body.appendChild(m);selectedSize='A3';}
function selectSize(b,s){selectedSize=s;document.querySelectorAll('.size-button').forEach(x=>{x.style.background='transparent';x.style.color='#111'});b.style.background='#111';b.style.color='#fff';}
function addToCart(id,size){const e=cart.find(x=>x.id===id&&x.size===size);if(e)e.quantity++;else cart.push({id,size,quantity:1});updateCart();openCart();}
function removeFromCart(id,size){cart=cart.filter(x=>!(x.id===id&&x.size===size));updateCart();}
function updateCart(){const count=byId('cart-count');if(count)count.textContent=cart.reduce((s,x)=>s+x.quantity,0);const c=byId('cart-items');if(!c)return;c.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id),price=i.size==='A1'?A1_PRICE:A3_PRICE;return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div class="cart-item-info"><strong>${p.name}</strong><p>${i.size} — ${price} JD</p><p>Qty: ${i.quantity}</p><button onclick="removeFromCart(${i.id},'${i.size}')">REMOVE</button></div><strong>${price*i.quantity} JD</strong></div>`}).join(''):'<p style="font-size:13px">Your cart is empty.</p>';const subtotal=cart.reduce((s,i)=>s+(i.size==='A1'?A1_PRICE:A3_PRICE)*i.quantity,0),total=cart.length?subtotal+DELIVERY:0;if(byId('cart-subtotal'))byId('cart-subtotal').textContent=`${subtotal} JD`;if(byId('cart-total'))byId('cart-total').textContent=`${total} JD`;if(byId('checkout-total'))byId('checkout-total').textContent=`${total} JD`;}
function openCart(){const e=byId('cart');if(e)e.classList.add('active');}function closeCart(){const e=byId('cart');if(e)e.classList.remove('active');}function openCheckout(){if(!cart.length)return alert('Your cart is empty.');closeCart();const e=byId('checkout');if(e)e.classList.add('active');}function closeCheckout(){const e=byId('checkout');if(e)e.classList.remove('active');}
function initCheckout(){const checkoutForm=byId('checkout-form');if(!checkoutForm)return;checkoutForm.addEventListener('submit',e=>{e.preventDefault();const n='#'+Math.floor(10000+Math.random()*90000),sub=cart.reduce((s,i)=>s+(i.size==='A1'?A1_PRICE:A3_PRICE)*i.quantity,0),total=sub+DELIVERY;if(byId('order-number'))byId('order-number').textContent=n;if(byId('payment-total'))byId('payment-total').textContent=`${total} JOD`;if(byId('payment-reference'))byId('payment-reference').textContent=`ORDER ${n}`;closeCheckout();const payment=byId('payment');if(payment)payment.classList.add('active');});}
function completePayment(){const p=byId('payment'),s=byId('success');if(p)p.classList.remove('active');if(s)s.classList.add('active');cart=[];updateCart();}function closeSuccess(){const s=byId('success');if(s)s.classList.remove('active');window.scrollTo({top:0,behavior:'smooth'});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderProducts();updateCart();initCheckout();});else{renderProducts();updateCart();initCheckout();}
